name: "Dev Skydera Preview Deploy Action"
description: "Get started with Python Container actions"
author: "Lecole Cole"
inputs:
  name:
    description: "Name of the deployed preview application"
    required: true
  skyNamespace:
    description: "Namespace to deploy the preview application"
    required: true
  skyGitIntgAccessId:
    description: "Github integration ID"
    required: true
  skyGitRepoSlug:
    description: "Application slug ID for the preview application"
    required: true
  skyApiKey:
    description: "Skydera API key"
    required: true
  skyCertId:
    description: "SSL Cert Id"
    required: true
  prNumber:
    description: "Pull request number"
    required: true
    default: ${{ github.event.number }}
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
